# Generated by Django 5.1.2 on 2024-10-24 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="client_id",
        ),
    ]
